### ISSUE TITLE
`xlsx` uploads fail on CommCare Bulk Upload API 

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/lwala#55] opened 2021-11-08 11:07 UTC
Recently uploading `xlsx` files to CommCare Bulk Upload API started failing with error: `The file uploaded has the following error: Excel xlsx file; not supported`

CommCare support confirmed there was no change in the API and xlsx uploads should work as previously. 

Here's a failed run https://www.openfn.org/projects/pdbmj5/runs/0618903b-52a6-7f14-a5e0-f606ccb07a39 on [this](https://www.openfn.org/projects/pdbmj5/messages/061836a3-98a2-75dd-b456-a5ae4513fffe) message

Job: https://www.openfn.org/projects/pdbmj5/messages/061836a3-98a2-75dd-b456-a5ae4513fffe

## Adaptor
`language-commcare`

## State
See LP for `OpenFn CommCareHQ (Lwala)`

**Comment by aleksa-krolls** [comment] 2021-11-09 07:29
@lakhassane @ritazagoni and I got some feedback from CommCare support: 
1. use an API key in authentication. See LP for `CommCare API Key` and these docs: https://confluence.dimagi.com/display/commcarepublic/Authentication#Authentication-ApiKeyauthentication
2. Re: the xlsx error - see below for their comment. 
We noticed that the file you sent to us was an .xls file and not excel, there were recent changes to how we read xls files so we suspect that the cause maybe the file extension. Would you be able to try the below suggested solutions and see if the issue gets resolved?

a. If possible, ensure that you save the upload file as just an Excel Workbook and not Excel 97-2003
OR
b. In the Api call, in the file parameter change the file extension of the file to upload to .xls

**Can you please make these changes and re-run the failure to see if that works?**

**Comment by lakhassane** [comment] 2021-11-09 12:06
@aleksa-krolls fixed using `Commcare@v1.4.0`: https://www.openfn.org/projects/pdbmj5/runs/0618a63d-3637-7316-89b4-427ee09dd9d7

Before closing this do you know if this ApiKey is something permanent (that we should add to our credentials)?. I created a raw json credential (see `Lwala CommCare HQ (Mamadou user)` in cred page) instead of the commcare credential that you used. 
But if it is permanent we can update bodyschema in platform to integrate the ApiKey.

**Comment by aleksa-krolls** [comment] 2021-11-09 12:13
Awesome, thanks @lakhassane. And for this CommCare implementation we will use the ApiKey going forward... and probably will for any CC implementation using the `bulk_upload_api`... so I agree that would be good to have a CommCare credential for this... keep in mind there might be some use cases were we want to use basic auth, but this will probably be the less frequently used option when writing data to CommCare. 

I

**Closed** 2021-11-09 13:13 UTC
