### ISSUE TITLE
Bulk upsert jobs to Salesforce failing with exit code 5

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/lwala#100] opened 2023-04-28 20:03 UTC
## Describe the bug
Hildah reported that the bulk upsert jobs that were developed last week are failing with an exit code 5. Find the failed runs below.  

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug:

- [WF1-2. Bulk upsert HHs and HH Visits](https://www.openfn.org/projects/staging-lwala-chw-support/runs/0644bafe-b6b1-7f99-803c-8f8c3a1cd600)
- [WF2-2. Bulk get Person casesBulk upsert Persons](https://www.openfn.org/projects/staging-lwala-chw-support/runs/0644bbfb-6af8-73c5-896e-d734bbd1a004)
- [WF4-2. Bulk upsert Services](https://www.openfn.org/projects/staging-lwala-chw-support/runs/0644bc35-7c07-75c0-ae76-0f3835b05cc4)

### expression.js
Link to the job itself in Github:

- https://github.com/OpenFn/lwala/blob/bulk-testing/commcare-salesforce-jobs/upsert_household_and_household_visit.js
- https://github.com/OpenFn/lwala/blob/bulk-testing/commcare-salesforce-jobs/Upsert-Person-Case-Update.js
- https://github.com/OpenFn/lwala/blob/bulk-testing/commcare-salesforce-jobs/Referrals-Upsert-Service_V2.js

### state.json

Parent job 
```json
{
 "configuration": { "SEE LP OpenFn CommCareHQ (Lwala) - PROD"}, 
"data": {"NA"}
"cursor": {"dynamic OR manual cursor 2023-01-01T00:00:00"}
}
```

Flow job
```json
{
 "configuration": {"SEE LP Lwala Salesforce Sandbox (Bulk 2023)"}, 
"data": {"data generated by parent jobs"}
}
```

## Expected behavior
These jobs should upsert the CommCare case data to Salesforce.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
3. [Please test the change on OpenFn.org by re-running the parent runs of the run links above and confirming success.]

## Toggl 
Lwala Bulk Workflows [2023]

**Comment by daissatou2** [comment] 2023-04-28 20:04
@aleksa-krolls please confirm the Lwala CommCare cred name before assigning to Mtuchi and Taylor.

**Comment by aleksa-krolls** [comment] 2023-05-03 07:31
Issue caused by flow Job 2 exceed job state limit of 10MB because too much data was extracted in Job 1. Marking as closed for now.

**Closed by aleksa-krolls** 2023-05-03 07:31 UTC
