### ISSUE TITLE
Bulk upsert HH and HV - Handle undefined locations TypeError [Error]: Cannot read properties of undefined (reading 'catchment')

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/lwala#106] opened 2023-05-02 23:49 UTC
## Background 
 See issue  #88. This is related to the bulk workflow for `Households and Household Visits `

## Issue
See run failure for Job 2 with error `TypeError [Error]: Cannot read properties of undefined (reading 'catchment')`
https://www.openfn.org/projects/staging-lwala-chw-support/runs/06450ee9-f50b-7067-a6ed-53bcc2857f2d

I think this is because a `catchment` ID is not found. If this is the case, then please return the id `'a00G5000003IFLUIA4'` as the value for `catchment` if a matching location cannot be found or if CommCare `owner_id` is blank. 

## expression
**Please work on the `bulk-testing` branch!!**
https://github.com/OpenFn/lwala/blob/bulk-testing/commcare-salesforce-jobs/upsert_household_and_household_visit.js

## state
**Run Job 1 (https://github.com/OpenFn/lwala/blob/bulk-testing/bulk/getCases-HH.js) to generate state for Job 2...**

**Job 1:** 
configuration: `SEE LP OpenFn CommCareHQ (Lwala) - PROD`
data: `{}`

**Job 2:** 
configuration: see LP Lwala Salesforce Sandbox (Bulk 2023)
data: use the final state from job 1

## output
If Job 1 gets `0` records from CommCare, then no action should happen in Job 2. 
If Job 1 gets `>0` records from CommCare, then sync each item as a HH and HV record to Salesforce.

**Comment by mtuchi** [comment] 2023-05-03 06:49
@daissatou2 i can not reproduce this error locally, i have created a PR for the error that i was facing while testing locally #107

**Comment by aleksa-krolls** [comment] 2023-05-03 07:26
Dupe of #103

**Closed by aleksa-krolls** 2023-05-03 07:26 UTC
